### ISSUE TITLE
High kernel_drops 

### ISSUE THREAD

**Issue by sanpichen** [pevma/SEPTun-Mark-II#3]
version:"5.0.2-dev (b9515671b 2019-12-13)"

my suricata drops lot of packets  when i increase stream.reassembly.memcap.

......
stream:
  memcap: 4gb
  checksum-validation: yes      # reject incorrect csums
  inline: auto                  # auto will use inline mode in IPS mode, yes or no set it statically
  reassembly:
    memcap: 6gb
    depth: 1mb                  # reassemble 1mb into a stream
    toserver-chunk-size: 2560
    toclient-chunk-size: 2560
    randomize-chunk-size: yes
    #randomize-chunk-range: 10
    #raw: yes
    #segment-prealloc: 2048
    #check-overlap-different-data: true
.....

Date: 12/24/2020 -- 16:10:48 (uptime: 0d, 00h 37m 41s)
------------------------------------------------------------------------------------
Counter                                       | TM Name                   | Value
------------------------------------------------------------------------------------
capture.kernel_packets                        | Total                     | 95678654
capture.kernel_drops                          | Total                     | 35796744
decoder.pkts                                  | Total                     | 59651457
decoder.bytes                                 | Total                     | 37606639412
decoder.invalid                               | Total                     | 21
decoder.ipv4                                  | Total                     | 59487908
decoder.ipv6                                  | Total                     | 11962
decoder.ethernet                              | Total                     | 59651457
decoder.tcp                                   | Total                     | 56754306
decoder.udp                                   | Total                     | 2129412
decoder.icmpv4                                | Total                     | 408461
decoder.icmpv6                                | Total                     | 584
decoder.vlan                                  | Total                     | 40640031
decoder.vxlan                                 | Total                     | 17
decoder.avg_pkt_size                          | Total                     | 630
decoder.max_pkt_size                          | Total                     | 65040
flow.tcp                                      | Total                     | 1015590
flow.udp                                      | Total                     | 485837
flow.icmpv4                                   | Total                     | 12139
flow.icmpv6                                   | Total                     | 247
decoder.event.ipv4.iplen_smaller_than_hlen    | Total                     | 20
decoder.event.ipv4.opt_pad_required           | Total                     | 347
decoder.event.ipv6.zero_len_padn              | Total                     | 217
decoder.event.tcp.hlen_too_small              | Total                     | 1
tcp.sessions                                  | Total                     | 810188
tcp.invalid_checksum                          | Total                     | 18
tcp.syn                                       | Total                     | 1492155
tcp.synack                                    | Total                     | 964728
tcp.rst                                       | Total                     | 656167
tcp.pkt_on_wrong_thread                       | Total                     | 1728003
tcp.stream_depth_reached                      | Total                     | 1992
tcp.reassembly_gap                            | Total                     | 41864
tcp.overlap                                   | Total                     | 8392278
detect.alert                                  | Total                     | 717
app_layer.flow.http                           | Total                     | 207817
app_layer.tx.http                             | Total                     | 340448
app_layer.flow.ftp                            | Total                     | 320
app_layer.tx.ftp                              | Total                     | 2671
app_layer.flow.smtp                           | Total                     | 1
app_layer.tx.smtp                             | Total                     | 1
app_layer.flow.tls                            | Total                     | 137498
app_layer.flow.ssh                            | Total                     | 674
app_layer.flow.dns_tcp                        | Total                     | 2
app_layer.tx.dns_tcp                          | Total                     | 6
app_layer.flow.ntp                            | Total                     | 7699
app_layer.tx.ntp                              | Total                     | 8744
app_layer.flow.ftp-data                       | Total                     | 123
app_layer.flow.dhcp                           | Total                     | 148
app_layer.tx.dhcp                             | Total                     | 1192
app_layer.flow.snmp                           | Total                     | 6675
app_layer.tx.snmp                             | Total                     | 62802
app_layer.flow.failed_tcp                     | Total                     | 114504
app_layer.flow.dcerpc_udp                     | Total                     | 334
app_layer.flow.dns_udp                        | Total                     | 237772
app_layer.tx.dns_udp                          | Total                     | 857433
app_layer.flow.failed_udp                     | Total                     | 233209
flow_mgr.closed_pruned                        | Total                     | 501179
flow_mgr.new_pruned                           | Total                     | 806868
flow_mgr.est_pruned                           | Total                     | 137239
flow.spare                                    | Total                     | 10541
flow.tcp_reuse                                | Total                     | 216
flow_mgr.flows_checked                        | Total                     | 10109
flow_mgr.flows_notimeout                      | Total                     | 8535
flow_mgr.flows_timeout                        | Total                     | 1574
flow_mgr.flows_timeout_inuse                  | Total                     | 151
flow_mgr.flows_removed                        | Total                     | 1423
flow_mgr.rows_checked                         | Total                     | 65536
flow_mgr.rows_skipped                         | Total                     | 59818
flow_mgr.rows_empty                           | Total                     | 576
flow_mgr.rows_maxlen                          | Total                     | 7
tcp.memuse                                    | Total                     | 78000360
tcp.reassembly_memuse                         | Total                     | 346047108
http.memuse                                   | Total                     | 235587976
ftp.memuse                                    | Total                     | 1466572
app_layer.expectations                        | Total                     | 13
flow.memuse                                   | Total                     | 31940152

if stream.reassembly.memcap scales to 256m ,the capture.kernel_drops  would down even to zero.
the TCP reassembly gaps increases  linely

help help me~

**Comment by sanpichen** [comment]
top show:

top - 17:08:49 up 15 days,  6:52,  4 users,  load average: 7.30, 5.73, 5.09
Tasks: 529 total,   1 running, 527 sleeping,   1 stopped,   0 zombie
%Cpu(s):  4.9 us,  0.3 sy,  1.4 ni, 93.0 id,  0.2 wa,  0.0 hi,  0.2 si,  0.0 st
KiB Mem : 13166155+total,  1522368 free, 70419664 used, 59719512 buff/cache
KiB Swap:        0 total,        0 free,        0 used. 59640008 avail Mem

   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
126094 logstash  20   0 39.431g 0.033t 0.029t S 147.2 27.3 141:24.54 Suricata-Main
 59972 elastic+  20   0  0.762t 0.026t 269608 S 102.0 21.4  17608:47 java
105217 logstash  39  19 12.291g 4.592g  58652 S  71.0  3.7 347:43.73 java
135107 root      20   0   47376   4236   3064 R   0.7  0.0   0:00.09 top
  1263 root       0 -20       0      0      0 S   0.3  0.0   0:16.06 kworker/35:1H
  2813 mongodb   20   0 1121464  45980      0 S   0.3  0.0 148:13.16 mongod
     1 root      20   0  204808   4880   3088 S   0.0  0.0   0:13.10 systemd

**Comment by pevma** [comment]
I suggest using the Suricata forums (https://forum.suricata.io/) for troubleshooting as this would bring more exposure/help and feedback. Could  you please post the question there?

**Comment by sanpichen** [comment]
YA,I would do thant ,Thank you all the same.

**Comment by pevma** [comment]
Could you please post  a link to the issue from here as well please , when you open it.
Looking forward to more details in the Suri forum to help you out.

**Comment by sanpichen** [comment]
here it is  :https://forum.suricata.io/t/high-number-kernel-drops-again/934
